### ISSUE TITLE
Forked - CrimeService updated 

### ISSUE THREAD

**Issue by Bisjob** [RobertWildgoose/PoliceAPI_Client#1]
Hi, thanks for your wrapper ! It is a nice code.
I forked your project and complete a bit the CrimeService, only for the StreetLevelCrimes and outcomes. 
I also created a small MAUI app with a map to test the data (I saw you have some MAUI project in your repo, you may be interested)
I'll probably improve it a bit in the next few days.
Feel free to take a look ;)

**Comment by RobertWildgoose** [comment]
Hey @Bisjob , thanks for the interest :)

This repo is on Nuget as a WIP package, if you did want to consume its here : https://www.nuget.org/packages/PoliceAPI_Client/

Ill make note of this in the readme, as just noticed i havent mentioned it

Also if you want to create a pr with your improvements/changes would be happy to merge in and push up the changes to the nuget package, but I don't think I have properly set the repo up so it can be contributed to will sort that tonight.

**Comment by Bisjob** [comment]
Yeah I saw your nuget but I needed the StreetLevelCrimes. And I saw not implemented in your code, that's why I forked it.

If you want to see my modifications you can see them here : https://github.com/RobertWildgoose/PoliceAPI_Client/compare/main...Bisjob:PoliceAPI_Client:main
I added 2 models, Coordinates and Polygon to help to perform the queries

**Comment by RobertWildgoose** [comment]
@Bisjob - I've absorbed some of your changes whilst also adding some extra validation and exceptions, this is in the process of uploading to Nuget so I'm going to close this issue now.

This will go out as Version 1.0.5
